### ISSUE TITLE
OSError: /usr/lib/libvcx.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Alexis-Falquier** [evernym/sdk#457]
when configuring through a python script the following error appears:
`OSError: /usr/lib/libvcx.so: cannot open shared object file: No such file or directory`

I noticed the cargo.toml file put libvcx.so in a debug directory.

I solved my issue by copying the libvcx.so file form the debug directory into my usr/lib dfirectory. I am creating this issue so that it exists and my solution is available, but also as it might be a build error in which it was supposed to put the file in the usr/lib directory but does not.

**Comment by hadleym** [comment]
Currently the intended way of installing the library is through a debian package, which will put the libvcx.so file into /usr/lib/libvcx.so with appropriate permissions.

Which field of the Cargo.toml file are you looking at to see it put it into a debug directory? I think you might have it flipped when interpreting the Cargo.toml file.  The [package.metadata.deb.assets] portion of the Cargo.toml indicate that we package into the debian from the target/debug/libvcx.so file.
