### ISSUE TITLE
LIBINDY_IOS_BUILD_URL invalid

### ISSUE THREAD

**Issue by phillipgibb** [evernym/sdk#488]
The shared functions script: sdk/vcx/libvcx/build_scripts/ios/mac/shared.functions.sh
uses:
export LIBSOVTOKEN_IOS_BUILD_URL="https://repo.corp.evernym.com/filely/ios/libsovtoken_0.9.1-201808311521-ca7b339_all.zip"

This url does not exist

**Comment by hadleym** [comment]
Yes, we'll need to migrate any internal dependencies on files to something that can at least be built locally.  Most likely we'll make this payment agnostic.
