### ISSUE TITLE
Issue With Building VCX

### ISSUE THREAD

**Issue by andrewBSTan** [evernym/sdk#497]
Hi, was going through the steps to build VCX but when doing Cargo Build, it gives an error.  Appreciate help here.
My environment is Ubuntu 18.04 and RUSTC Version 1.25.0
Below is the error message when running Cargo Build --verbose
![image](https://user-images.githubusercontent.com/37392630/45260864-0aa25300-b425-11e8-867a-33aeeb04940e.png)

**Comment by hadleym** [comment]
parking_lot_core v3.0 has a dependency on rust v1.26.  (v3.1 interestingly has a minimum dependency on 1.24).
I would suggest updating both rust and parking_lot_core (perhaps a `cargo update`).
We are all using at least rust v1.28.
